### ISSUE TITLE
Subscription do not have field snap_to_nth_day

### ISSUE THREAD

**Issue by bilalsha** [Invoiced/invoiced-java#6]
In api document https://invoiced.com/docs/api/?java#create-a-subscription `snap_to_nth_day` is specified but in java client code Subscription class its not there. Is there a way to set it?

**Comment by jaredtking** [comment]
Thank you for the feedback! You should be able to set the `snapToNthDay` parameter on the subscription object. For example, you would use `subscription.snapToNthDay = 1` to use calendar billing with the 1st day of the month as the renewal date.
